### ISSUE TITLE
Did not attach multiple files

### ISSUE THREAD

**Issue by AlexeyAG** [znuny/Znuny4OTRS-AttachmentMultiUpload#4] opened 2015-06-18 06:20 UTC
I am trying to use plugin on clean otrs4 instalation.
I connected repository via opm and successfuly install this plugin.
Now I can select two or more files in customer compose form, but after
selection of files, form is reloaded and no files are attached.
One file can be attached without issues.
Did your plugin tested on otrs4?

**Comment by thorsteneckel** [comment] 2015-06-18 07:30
Hi @AlexeyAG !

Thanks for using our free addon and giving us feedback on it. You were right, there was an issue with uploading multiple attachments in the customer interface. We already found, fixed it and created the new version '1.1.2' you can easily install and use in your system via the Znuny4OTRS-Repo.

It would be great if you could provide some feedback.

Best Regards,
  Thorsten

**Comment by AlexeyAG** [comment] 2015-06-18 12:16
Thank you for quick response.
For otrs v4 attachments of two or more files is working now.
I am waiting for updates in REPO to setup working version on otrs v3.3.

**Comment by thorsteneckel** [comment] 2015-06-18 12:23
Thanks for your support finding that issue. OTRS 3.x versions of this addon were not affected so I'm closing this issue.

**Comment by AlexeyAG** [comment] 2015-06-18 12:46
Nevertheless, files in otrs v3.3 can't attache multiple files now. :-( I see an  error message in log file:
[Thu Jun 18 15:25:44 2015][Error][Kernel::System::Web::UploadCache::DB::FormIDAddFile][66] Need Filename!
Plugin installed from repo the same way as for otrs version 4

**Comment by thorsteneckel** [comment] 2015-06-18 12:56
Could you please provide the following information to make it possible for me to reproduce the issue:

Which OTRS 3.3 patch level version exactly are you using?
Which browser are you using?
In which interface occurs the error, agent or/and customer?
In wich action (e.g. CustomerTicketMessage) occurs the error?

**Comment by AlexeyAG** [comment] 2015-06-18 13:07
1)  OTRS 3.3.13 
2) IE 11 AND Google Chome 43.0 - both gives the save result
3) Agent interface and customer the same result
4) Any Action any form ( new ticket and reply an customer FollowUp)

**Comment by thorsteneckel** [comment] 2015-06-18 13:11
This sounds a bit like a compatibility issue. Have you any other packages installed? Could you provide a list of installed packages?

**Comment by AlexeyAG** [comment] 2015-06-18 14:13
FAQ
GeneralCatalog 
ImportExport 
iPhoneHandle 
ITSM 
ITSMChangeManagement 
ITSMConfigurationManagement 
ITSMCore 
ITSMIncidentProblemManagement 
ITSMServiceLevelManagement 
OTRSMasterSlave 
Support 
Survey 
TimeAccounting 
Znuny4OTRS-AttachmentMultiUpload 
Znuny4OTRS-Repo

**Comment by thorsteneckel** [comment] 2015-06-18 14:43
I can't reproduce the error you're describing. I created a 3.3.13 test system with the latest package versions. Please tell me if you can reproduce your error in my test system:

URL: http://vz451.demo.znuny.com/otrs/index.pl
User: root@localhost
PW: multiupload

**Comment by AlexeyAG** [comment] 2015-06-18 14:53
Your test system working fine! :-)

**Comment by thorsteneckel** [comment] 2015-06-18 15:04
So the error has to be in your system. If you need commercial support please contact us as support@znuny.com

**Closed by thorsteneckel** 2015-06-18 15:04 UTC

**Comment by AlexeyAG** [comment] 2015-06-19 08:09
Yes, you are right! Thank you for your help!
